In [29]:
import numpy as np
score=np.array([[1,2,3,3],[4,5,6,3],[7,8,9,3],[10,11,12,3]])
y=np.array([2,1,2,3])
x=np.array(range(4))
print(x)
score=score[y]
score[x,y]=0
print(score)

[0 1 2 3]
[[ 7  8  0  3]
 [ 4  0  6  3]
 [ 7  8  0  3]
 [10 11 12  0]]
